version: '2'
services:
  web70:
    image: bluespice/web:REL1_27
    ports:
      - "80:80"
    links:
      - database
      - mail
      - app_solr
      - app_bshtml2pdf
    volumes:
      - ./webroot:/var/www/html
      - ./configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ~/.ssh:/root/.ssh.host
      - ~/.composer:/root/.composer
    working_dir: /var/www
  database:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - ./databases:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=l4Dd7A83bn$!74b39$0v
  app_solr:
    image: bluespice/solr:REL1_27
    ports:
      - "8080:8080"
    volumes:
      - ./searchindex:/opt/bluespice/data/solr/bluespice/data
  app_bshtml2pdf:
    image: bluespice/bshtml2pdf:REL1_27
    ports:
      - "8084:8080"
  parsoid:
    image: bluespice/parsoid:REL1_27
    ports:
      - "8000:8000"
    volumes:
      - ./configs/parsoid:/opt/parsoid/config
  mail:
    image: mailhog/mailhog
    ports:
      - "18025:8025"
      - "1025:1025"
