version: '2'
services:
  web73:
    image: bluespice/web:REL1_31
    ports:
      - "80:80"
    links:
      - database
      - mail
      - app_bshtml2pdf
      - app_bshtml2docx
      - app_bshtmldiff
      - app_bspagepreviewimage
      - app_parsoid
      - app_mathoid
      - app_elasticsearch
    volumes:
      - ./webroot:/var/www/html
      - ./configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www
  database:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - ./databases:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hallowelt
  app_bshtml2pdf:
    image: bluespice/bshtml2pdf:REL1_31
    ports:
      - "8080:8080"
  app_bshtmldiff:
    image: bluespice/bshtmldiff:REL1_31
    ports:
      - "8080:8080"
  app_bshtml2docx:
    image: bluespice/bshtml2docx:REL1_31
    ports:
      - "80:80"
  app_parsoid:
    image: bluespice/parsoid:REL1_31
    ports:
      - "8000:8000"
  app_mathoid:
    image: wikimedia/mathoid:latest
    ports:
      - "8000:8000"
  app_elasticsearch:
    image: wikimedia/mathoid:latest
    ports:
      - "8000:8000"
  mail:
    image: mailhog/mailhog
    ports:
      - "18025:8025"
      - "1025:1025"
